
srcDir: src/
cssSrcDir: src/css/
cssDestDir: css/
jsSrcDir: src/js/
jsDestDir: js/
imgSrcDir: src/img/
imgDestDir: img/

viewsSrcDir: src/views/
viewsDestDir: views/
viewsCssSrcDir: src/views/css/
viewsCssDestDir: views/css/
viewsJsSrcDir: src/views/js/
viewsJsDestDir: views/js/
viewsImgSrcDir: src/views/images/
viewsImgDestDir: views/images/